# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: predict.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rpredict.proto\x12\x12onnxruntime.server\x1a\ronnx-ml.proto"\xaf\x01\n\x0ePredictRequest\x12>\n\x06inputs\x18\x02 \x03(\x0b\x32..onnxruntime.server.PredictRequest.InputsEntry\x12\x15\n\routput_filter\x18\x03 \x03(\t\x1a@\n\x0bInputsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12 \n\x05value\x18\x02 \x01(\x0b\x32\x11.onnx.TensorProto:\x02\x38\x01J\x04\x08\x01\x10\x02"\x97\x01\n\x0fPredictResponse\x12\x41\n\x07outputs\x18\x01 \x03(\x0b\x32\x30.onnxruntime.server.PredictResponse.OutputsEntry\x1a\x41\n\x0cOutputsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12 \n\x05value\x18\x02 \x01(\x0b\x32\x11.onnx.TensorProto:\x02\x38\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "predict_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._options = None
    _globals["_PREDICTREQUEST_INPUTSENTRY"]._options = None
    _globals["_PREDICTREQUEST_INPUTSENTRY"]._serialized_options = b"8\001"
    _globals["_PREDICTRESPONSE_OUTPUTSENTRY"]._options = None
    _globals["_PREDICTRESPONSE_OUTPUTSENTRY"]._serialized_options = b"8\001"
    _globals["_PREDICTREQUEST"]._serialized_start = 53
    _globals["_PREDICTREQUEST"]._serialized_end = 228
    _globals["_PREDICTREQUEST_INPUTSENTRY"]._serialized_start = 158
    _globals["_PREDICTREQUEST_INPUTSENTRY"]._serialized_end = 222
    _globals["_PREDICTRESPONSE"]._serialized_start = 231
    _globals["_PREDICTRESPONSE"]._serialized_end = 382
    _globals["_PREDICTRESPONSE_OUTPUTSENTRY"]._serialized_start = 317
    _globals["_PREDICTRESPONSE_OUTPUTSENTRY"]._serialized_end = 382
# @@protoc_insertion_point(module_scope)
